# Generated by Django 4.1 on 2023-08-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_image', models.ImageField(upload_to='app1/media/team')),
                ('member_name', models.CharField(max_length=50)),
                ('member_designation', models.CharField(max_length=50)),
                ('member_des', models.TextField()),
            ],
        ),
    ]
