# Generated by Django 4.1 on 2023-08-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_icon', models.ImageField(upload_to='app1/media/feature')),
                ('feature_title', models.CharField(max_length=50)),
                ('feature_des', models.TextField()),
            ],
        ),
    ]
