# Generated by Django 4.1 on 2023-08-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=70)),
                ('product_des', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('del_price', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(upload_to='app1/media/product2')),
                ('icon', models.ImageField(upload_to='app1/media/product2')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
