# Generated by Django 4.1 on 2023-08-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_product2_alter_contactform_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product2',
            old_name='icon',
            new_name='Product_icon',
        ),
        migrations.RenameField(
            model_name='product2',
            old_name='image',
            new_name='Product_image',
        ),
    ]
