# Generated by Django 4.1 on 2023-08-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_icon_product2_product_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=100)),
                ('email1', models.EmailField(blank=True, max_length=50, null=True)),
                ('subject1', models.CharField(blank=True, max_length=50, null=True)),
                ('message1', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username2', models.CharField(max_length=100)),
                ('email2', models.EmailField(blank=True, max_length=50, null=True)),
                ('subject2', models.CharField(blank=True, max_length=50, null=True)),
                ('message2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
