# Generated by Django 4.1 on 2023-09-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_signup_email_signup_email1_signup_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallerysa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='app1/media/gallerysa')),
            ],
        ),
        migrations.CreateModel(
            name='Galleryso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='app1/media/galleryso')),
            ],
        ),
        migrations.CreateModel(
            name='Product3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=70)),
                ('product_des', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('del_price', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
                ('Product_image', models.ImageField(upload_to='app1/media/product3')),
                ('Product_icon', models.ImageField(upload_to='app1/media/product3')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
